package com.pacoillan.pojo;
// Generated 26-mar-2014 23:27:29 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name="modelo"
    ,catalog="bbdd_prueba"
)
public class Modelo  implements java.io.Serializable {


     private Integer idmodelo;
     private Motor motor;
     private String codigo;
     private String descripcion;

    public Modelo() {
    }

    public Modelo(Motor motor, String codigo, String descripcion) {
       this.motor = motor;
       this.codigo = codigo;
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idmodelo", unique=true, nullable=false)
    public Integer getIdmodelo() {
        return this.idmodelo;
    }
    
    public void setIdmodelo(Integer idmodelo) {
        this.idmodelo = idmodelo;
    }

    public Motor getMotor() {
        return this.motor;
    }
    
    public void setMotor(Motor motor) {
        this.motor = motor;
    }
    
    @Column(name="codigo", nullable=false, length=10)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="descripcion", nullable=false, length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


