package com.pacoillan.pojo;
// Generated 26-mar-2014 23:27:29 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Motor generated by hbm2java
 */
@Entity
@Table(name="motor"
    ,catalog="bbdd_prueba"
)
public class Motor implements java.io.Serializable {


     private Integer idmotor;
     private String codigo;
     private String descripcion;
     private String cilindrada;
     private String kilowatios;
    

    public Motor() {    }

	
    public Motor(String codigo, String descripcion, String cilindrada, String kilowatios) {
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.cilindrada = cilindrada;
        this.kilowatios = kilowatios;
    }
    
   
    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idmotor", unique=true, nullable=false)
    public Integer getIdmotor() {
        return this.idmotor;
    }
    
    public void setIdmotor(Integer idmotor) {
        this.idmotor = idmotor;
    }
    
    @Column(name="codigo", nullable=false, length=10)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="descripcion", nullable=false, length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="cilindrada", nullable=false, length=10)
    public String getCilindrada() {
        return this.cilindrada;
    }
    
    public void setCilindrada(String cilindrada) {
        this.cilindrada = cilindrada;
    }
    
    @Column(name="kilowatios", nullable=false)
    public String getKilowatios() {
        return this.kilowatios;
    }
    
    public void setKilowatios(String kilowatios) {
        this.kilowatios = kilowatios;
    }


}


